# Site settings
title: Achmad Gozali
description: 'Just buy me coffe, and your project absolutely done'
url: ''
baseurl: 'https://achmadgozali8.github.io'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Achmad Gozali'
  email: achmadg6@gmail.com
  facebook_username: AchmadGozali
  github_username:  AchmadGozali8
  linkedin_username:  achmad-gozali-32b840130

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
